spring.application.name=Kafka
spring.kafka.bootstrap-servers=kafka-0:9094
spring.kafka.streams.bootstrap-servers=kafka-0:9094
spring.kafka.streams.properties.bootstrap.servers=kafka-0:9094
spring.kafka.streams.application-id=chat-filter-service
spring.kafka.streams.state-dir=/tmp/kafka-streams